name: Daily Holded Orders Report
on:
  schedule:
    # 06:00 UTC ≈ 08:00 Madrid en verano (CEST). En invierno (CET) sería 07:00 UTC.
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        env:
          HOLDED_API_KEY: ${{ secrets.HOLDED_API_KEY }}
          HOLDED_USE_BEARER: ${{ secrets.HOLDED_USE_BEARER }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_TO: ${{ secrets.MAIL_TO }}
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
        run: |
          python mail.py
